MLK-16164 Fix mxc_cec_test build break
The following error occurs when building with Yocto:

|       LD      mxc_cec_test/mxc_cec_test.out
| arm-poky-linux-gnueabi-gcc  -march=armv7-a -mfpu=neon  -mfloat-abi=hard -mcpu=cortex-a9 --sysroot=/home/r60874/morty/build-xwayland/tmp/sysroots/imx6qsabresd -L/home/r60874/morty/build-xwayland/tmp/sysroots/imx6qsabresd/usr/lib -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed mxc_cec_test/mxc_cec_test.o -lpthread -lcec -lrt -lstdc++ -o mxc_cec_test/mxc_cec_test.out
| /home/r60874/morty/build-xwayland/tmp/sysroots/imx6qsabresd/usr/lib/libcec.so: undefined reference to `pthread_detach'
| /home/r60874/morty/build-xwayland/tmp/sysroots/imx6qsabresd/usr/lib/libcec.so: undefined reference to `pthread_create'
| collect2: error: ld returned 1 exit status

The option -pthread was recently removed, causing this regression.

http://sw-stash.freescale.net/projects/IMX/repos/linux-test/diff/test/mxc_cec_test/Makefile?until=3c724843029a18d3af10e06389426303837e1364

The build break is fixed by restoring the option.

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>