MLK-15318-3 mxc_vpu_test: make variables static
Currently the mxc_vpu_test is build with gcc *.c. If we switch to
build with gcc -c and then ld/gcc *.o we will run into the following
error:

     LD	   mxc_vpu_test/mxc_vpu_test.out
mxc_vpu_test/transcode.o:(.bss+0x0): multiple definition of `dec'
mxc_vpu_test/loopback.o:loopback.c:(.bss+0x0): first defined here
mxc_vpu_test/transcode.o: In function `saveCropYuvImageHelper':
/home/tavi/src/linux-test/test/mxc_vpu_test/transcode.c:112: multiple definition of `enc'
mxc_vpu_test/loopback.o:/home/tavi/src/linux-test/test/mxc_vpu_test/loopback.c:354: first defined here
collect2: error: ld returned 1 exit status

Signed-off-by: Octavian Purdila <octavian.purdila@nxp.com>