mxc_v4l2_test: fix compilation error produced by gcc9
Fix trivial compilation error when GCC9 is used:

error: call to '__open_missing_mode' declared with attribute error: open
with O_CREAT or O_TMPFILE in second argument needs 3 arguments

This is now caused by not explicitly supplying the mode when O_CREAT is
used as disposition.

Signed-off-by: Andrey Zhizhikin <andrey.zhizhikin@leica-geosystems.com>
Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>